name: Dependency Updates

on:
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
        if: hashFiles('**/package.json') != ''

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
        if: hashFiles('**/requirements.txt', '**/pyproject.toml') != ''

      - name: Update npm dependencies
        if: hashFiles('**/package.json') != ''
        run: |
          npx npm-check-updates -u
          npm install

      - name: Update Python dependencies
        if: hashFiles('**/requirements.txt') != ''
        run: |
          pip install pip-tools
          pip-compile --upgrade requirements.in || pip-compile --upgrade requirements.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated Dependency Updates"
          body: |
            This PR updates dependencies to their latest versions.

            Please review the changes and test thoroughly before merging.

            Auto-generated by GitHub Actions 🤖
          branch: automated/dependency-updates
          delete-branch: true
