name: Setup Branch Protection

on:
  repository_dispatch:
    types: [setup-protection]
  workflow_dispatch:

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Protect main branch
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['security-checks', 'lint-javascript', 'lint-python']
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                require_last_push_approval: true
              },
              required_linear_history: false,
              allow_force_pushes: false,
              allow_deletions: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true,
              restrictions: null
            });

      - name: Protect dev branch
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'dev',
              required_status_checks: {
                strict: true,
                contexts: ['security-checks', 'lint-javascript', 'lint-python']
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                require_last_push_approval: true
              },
              required_linear_history: true,
              allow_force_pushes: false,
              allow_deletions: false, 
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true,
              restrictions: null
            });

      - name: Comment protection setup complete
        uses: actions/github-script@v7
        with:
          script: |
            console.log('✅ Branch protection rules configured for main and dev branches');
            console.log('🔒 Features enabled:');
            console.log('  - Required pull request reviews (1 approval)');
            console.log('  - Dismiss stale reviews when new commits are pushed');
            console.log('  - Require review from code owners');
            console.log('  - Require approval of most recent reviewable push');
            console.log('  - Require status checks to pass before merging');
            console.log('  - Require linear history');
            console.log('  - Require conversation resolution before merging');
            console.log('  - Prevent force pushes and deletions');
