name: PR Guard

on:
  workflow_call:

jobs:
  block-main-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Fail PRs into main (unless from dev)
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'dev'
        run: |
          echo "❌ Direct PRs to main are not allowed. Please PR into dev instead."
          exit 1
