# File: .github/.github/workflows/prettier-format.yml
name: Reusable - Prettier Auto-Formatter

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  format-and-commit:
    name: Format Code with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check for relevant file changes
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.{js,jsx,ts,tsx,json,css,scss,md,html,vue}
            **/.prettierrc*
            **/prettier.config.js

      - name: Checkout PR Branch
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          elif [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          elif [ -f "package.json" ]; then
            npm install
          else
            npm install prettier
          fi

      - name: Run Prettier Formatter
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npx prettier --write . --log-level warn

      - name: Check for formatting changes
        if: steps.changed-files.outputs.any_changed == 'true'
        id: git-check
        run: |
          if ! git diff --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "FILES_FORMATTED=$(git status --porcelain | wc -l)" >> $GITHUB_ENV
          git add .
          git commit -m "style: ✨ auto-format with Prettier"
          git push

      - name: Comment on PR
        if: steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const hasChanges = '${{ steps.git-check.outputs.has_changes }}' === 'true';
            const filesFormatted = process.env.FILES_FORMATTED || '0';
            let comment = `## 🎨 Prettier Formatting Results\n\n`;
            if (hasChanges) {
              comment += `✨ **Auto-formatted**: ${filesFormatted} file(s) with Prettier!\n`;
              comment += `📝 Changes have been automatically committed to this PR.`;
            } else {
              comment += `✅ **Formatting**: All files are already properly formatted.`;
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Report no relevant files changed
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No JS/TS/etc. files changed. Skipping Prettier formatting."
