# File: .github/.github/workflows/release-drafter.yml
name: Reusable - Release Drafter

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          # Tell Release Drafter where to find its config file in the central repo.
          # Assumes the config is at .github/.github/release-drafter.yml
          config-name: Homies-Tech-Innovation/.github/.github/release-drafter.yml@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
