# File: .github/.github/workflows/release-drafter.yml
name: Reusable - Release Drafter

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          # Provide the path to the config file *relative to the root* of the .github repository.
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
